export const FETCH_APPOINTMENT_LOADING = "FETCH_APPOINTMENT_LOADING";
export const FETCH_APPOINTMENT_SUCCESS = "FETCH_APPOINTMENT_SUCCESS";
export const FETCH_APPOINTMENT_ERROR = "FETCH_APPOINTMENT_ERROR";

export const VALIDATE_APPOINTMENT_SUCCESS = "VALIDATE_APPOINTMENT_SUCCESS";
export const VALIDATE_APPOINTMENT_ERROR = "VALIDATE_APPOINTMENT_ERROR";

export const GENERATE_APPOINTMENT_SUCCESS = "GENERATE_APPOINTMENT_SUCCESS";
export const GENERATE_APPOINTMENT_ERROR = "GENERATE_APPOINTMENT_ERROR";

export const REPORT_APPOINTMENT_SUCCESS = "REPORT_APPOINTMENT_SUCCESS";
export const REPORT_APPOINTMENT_ERROR = "REPORT_APPOINTMENT_ERROR";
export const REPORT_APPOINTMENT_LOADING = "REPORT_APPOINTMENT_LOADING";

export const DELAYED_APPOINTMENT_SUCCESS = "DELAYED_APPOINTMENT_SUCCESS";
export const DELAYED_APPOINTMENT_ERROR = "DELAYED_APPOINTMENT_ERROR";
export const DELAYED_APPOINTMENT_LOADING = "DELAYED_APPOINTMENT_LOADING";
