export const FETCH_CITIZEN_SUCCESS = "FETCH_CITIZEN_SUCCESS";
export const FETCH_CITIZEN_LOADING = "FETCH_CITIZEN_LOADING";
export const FETCH_CITIZEN_ERROR = "FETCH_CITIZEN_ERROR";
export const FETCHALL_CITIZENS_SUCCESS = "FETCHALL_CITIZENS_SUCCESS";
export const FETCHAll_CITIZENS_ERROR = "FETCHALL_CITIZENS_ERROR";

export const UPDATE_CITIZEN_SUCCESS = "UPDATE_CITIZEN_SUCCESS";
export const UPDATE_CITIZEN_ERROR = "UPDATE_CITIZEN_ERROR";

export const BOOK_APPOINTMENT_SUCCESS = "BOOK_APPOINTMENT_SUCCESS";
export const BOOK_APPOINTMENT_LOADING = "BOOK_APPOINTMENT_LOADING";
export const BOOK_APPOINTMENT_ERROR = "BOOK_APPOINTMENT_ERROR";

export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS";
export const GET_REPORT_LOADING = "GET_REPORT_LOADING";
export const GET_REPORT_ERROR = "GET_REPORT_ERROR";
