// add pharmacy types
export const ADD_PHARMACY_SUCCESS = "ADD_PHARMACY_SUCCESS";
export const ADD_PHARMACY_ERROR = "ADD_PHARMACY_ERROR";
//fetch pharmacies types
export const FETCH_PHARMACY_SUCCESS = "FETCH_PHARMACY_SUCCESS";
export const FETCH_PHARMACY_LOADING = "FETCH_PHARMACY_LOADING";
export const FETCH_PHARMACY_ERROR = "FETCH_PHARMACY_ERROR";
// delete pharmacy types
export const DELETE_PHARMACY_SUCCESS = "DELETE_PHARMACY_SUCCESS";
export const DELETE_PHARMACY_ERROR = "DELETE_PHARMACY_ERROR";
// update pharmacy types
export const UPDATE_PHARMACY_SUCCESS = "UPDATE_PHARMACY_SUCCESS";
export const UPDATE_PHARMACY_ERROR = "UPDATE_PHARMACY_ERROR";
