export const ADD_VOLUNTEER_SUCCESS = "ADD_VOLUNTEER_SUCCESS";
export const ADD_VOLUNTEER_ERROR = "ADD_VOLUNTEER_ERROR";

export const FETCH_VOLUNTEER_SUCCESS = "FETCH_VOLUNTEER_SUCCESS";
export const FETCH_VOLUNTEER_ERROR = "FETCH_VOLUNTEER_ERROR";
export const FETCH_VOLUNTEER_LOADING = "FETCH_VOLUNTEER_LOADING";

export const DELETE_VOLUNTEER_SUCCESS = "DELETE_VOLUNTEER_SUCCESS";
export const DELETE_VOLUNTEER_ERROR = "DELETE_VOLUNTEER_ERROR";

export const UPDATE_VOLUNTEER_SUCCESS = "UPDATE_VOLUNTEER_SUCCESS";
export const UPDATE_VOLUNTEER_ERROR = "UPDATE_VOLUNTEER_ERROR";
